export interface AgentCaptureRuntime {
  serverVersion: string;
  toolsCount: number;
  resourcesCount: number;
  promptsCount: number;
}

interface AgentCaptureSurface {
  id: string;
  name: string;
  agent_type: string;
  audience: string;
  status: "live" | "ready" | "monitored" | "stale" | "blocked" | "candidate";
  priority: "core" | "high" | "medium" | "watch";
  packrift_owned: boolean;
  canonical_url: string;
  install_or_call: string;
  proof_url: string;
  fallback_url?: string;
  next_action: string;
  notes?: string;
}

interface AgentHostFastPath {
  source: string;
  target: string;
  host: string;
  audience: string;
  source_aware_endpoint: string;
  tracked_install_url: string;
  tracked_first_run_url: string;
  tracked_first_run_shell_url: string;
  first_run_shell_one_liner: string;
  reviewer_activation_url: string;
  reviewer_activation_shell_url: string;
  order_handoff_url: string;
  order_handoff_shell_url: string;
  order_handoff_shell_one_liner: string;
  eval_pack_url: string;
  success_gate: string;
}

function surface(row: AgentCaptureSurface): AgentCaptureSurface {
  return row;
}

const MCP_ENDPOINT = "https://mcp.packrift.com/mcp";

function sourceAwareEndpoint(source: string, target: string): string {
  return `${MCP_ENDPOINT}?packrift_mcp_source=${source}&packrift_mcp_target=${target}`;
}

function firstRunShellUrl(source: string, target: string): string {
  return `https://mcp.packrift.com/r/run/${source}/${target}?format=sh`;
}

function orderHandoffShellUrl(source: string): string {
  return `https://mcp.packrift.com/r/order/${source}?format=sh`;
}

function hostFastPath(input: { source: string; target: string; host: string; audience: string; success_gate?: string }): AgentHostFastPath {
  const shellUrl = firstRunShellUrl(input.source, input.target);
  const orderShellUrl = orderHandoffShellUrl(input.source);
  return {
    source: input.source,
    target: input.target,
    host: input.host,
    audience: input.audience,
    source_aware_endpoint: sourceAwareEndpoint(input.source, input.target),
    tracked_install_url: `https://mcp.packrift.com/r/install/${input.source}/${input.target}?format=html`,
    tracked_first_run_url: `https://mcp.packrift.com/r/run/${input.source}/${input.target}?format=html`,
    tracked_first_run_shell_url: shellUrl,
    first_run_shell_one_liner: `curl -sS '${shellUrl}' | bash`,
    reviewer_activation_url: `https://mcp.packrift.com/r/activate/${input.source}?format=html`,
    reviewer_activation_shell_url: `https://mcp.packrift.com/r/activate/${input.source}?format=sh`,
    order_handoff_url: `https://mcp.packrift.com/r/order/${input.source}?format=html`,
    order_handoff_shell_url: orderShellUrl,
    order_handoff_shell_one_liner: `curl -sS '${orderShellUrl}' | bash`,
    eval_pack_url: `https://mcp.packrift.com/ai/mcp-eval-pack.json?source=${input.source}`,
    success_gate:
      input.success_gate ??
      "Run tools/list, get_cart_handoff_candidates, get_pricing, check_inventory, and create_cart_url from a real external MCP host; count the source only when the measured /r/cart URL is returned.",
  };
}

export const AGENT_HOST_FAST_PATHS: AgentHostFastPath[] = [
  hostFastPath({
    source: "mcp_so",
    target: "generic_streamable_http",
    host: "MCP.so",
    audience: "MCP directory users and reviewers who already produced source-aware tool calls and now need buyer/order proof.",
    success_gate:
      "Use the measured source-aware cart handoff in a real buyer or reviewer procurement flow, then watch for an MCP-attributed order or revenue event.",
  }),
  hostFastPath({
    source: "cline_mcp_marketplace",
    target: "cline",
    host: "Cline",
    audience: "Cline users installing Packrift from the Cline MCP Marketplace issue/listing path.",
  }),
  hostFastPath({
    source: "glama_connector",
    target: "glama_connector",
    host: "Glama",
    audience: "Glama connector users and reviewers validating the hosted Packrift MCP connector.",
  }),
  hostFastPath({
    source: "browse_sh",
    target: "generic_streamable_http",
    host: "Browserbase Browse",
    audience: "Browse/browser-skill agents installing Packrift from the open-web skill catalog.",
  }),
  hostFastPath({
    source: "docker_mcp_catalog",
    target: "generic_streamable_http",
    host: "Docker MCP Catalog",
    audience: "Docker MCP Catalog reviewers or users validating Packrift as a hosted remote MCP server.",
  }),
  hostFastPath({
    source: "cursor_directory",
    target: "cursor_windsurf_vscode",
    host: "Cursor",
    audience: "Cursor users and plugin-directory reviewers adding Packrift as a remote MCP server.",
  }),
  hostFastPath({
    source: "windsurf_direct",
    target: "cursor_windsurf_vscode",
    host: "Windsurf",
    audience: "Windsurf users adding Packrift through remote MCP JSON config.",
  }),
  hostFastPath({
    source: "codex_remote_mcp",
    target: "codex",
    host: "Codex",
    audience: "Codex workspaces adding Packrift without a duplicate local CLI.",
  }),
  hostFastPath({
    source: "claude_remote_mcp",
    target: "claude_code",
    host: "Claude",
    audience: "Claude Code and Claude Desktop users adding Packrift as a remote HTTP MCP server.",
  }),
  hostFastPath({
    source: "openai_chatgpt",
    target: "generic_streamable_http",
    host: "OpenAI / ChatGPT agents",
    audience: "OpenAI and ChatGPT-style agents that can call a remote Streamable HTTP MCP endpoint.",
  }),
  hostFastPath({
    source: "curated_ucp_storefront",
    target: "generic_streamable_http",
    host: "Curated UCP storefronts",
    audience: "Builders of curated Shopify UCP storefronts that need Packrift as the packaging and shipping-supplies merchant.",
  }),
  hostFastPath({
    source: "stack412_style_storefront",
    target: "generic_streamable_http",
    host: "Stack412-style storefronts",
    audience: "Automated storefront builders aggregating Shopify global-catalog products into shipping-supplies or fulfillment shelves.",
  }),
  hostFastPath({
    source: "plugthatshop_style_embed",
    target: "generic_streamable_http",
    host: "PlugThatShop-style embeds",
    audience: "Contextual shoppable embed builders that need a Packrift packaging shelf or packaging upsell path.",
  }),
  hostFastPath({
    source: "open_scout_shopping_agent",
    target: "generic_streamable_http",
    host: "Open Scout-style shopping agents",
    audience: "Shopping-agent builders routing packaging intents from chat, web, SMS, or WhatsApp into exact Packrift SKUs and measured cart handoff.",
  }),
  hostFastPath({
    source: "upsonic_ucp_agent_framework",
    target: "generic_streamable_http",
    host: "Upsonic-style UCP agent frameworks",
    audience: "Multi-agent UCP framework builders using Packrift as the packaging workflow example for discovery, filtering, live checks, and cart handoff.",
  }),
  hostFastPath({
    source: "agorio_shopping_agent_sdk",
    target: "generic_streamable_http",
    host: "Agorio shopping-agent SDK",
    audience: "UCP/ACP shopping-agent SDK builders using Packrift as the packaging merchant example for exact-spec MCP search and buyer-confirmed handoff.",
  }),
  hostFastPath({
    source: "langchain_agent",
    target: "generic_streamable_http",
    host: "LangChain",
    audience: "LangChain agent workflows that can mount remote MCP tools for procurement actions.",
  }),
  hostFastPath({
    source: "llamaindex_agent",
    target: "generic_streamable_http",
    host: "LlamaIndex",
    audience: "LlamaIndex workflows that need exact-spec product lookup plus measured cart handoff.",
  }),
  hostFastPath({
    source: "n8n_automation",
    target: "generic_streamable_http",
    host: "n8n",
    audience: "n8n automation builders wiring packaging procurement into agent or ops workflows.",
  }),
  hostFastPath({
    source: "zapier_automation",
    target: "generic_streamable_http",
    host: "Zapier",
    audience: "Zapier and automation users who need no-auth remote MCP product and cart tools.",
  }),
  hostFastPath({
    source: "mcp_inspector",
    target: "generic_streamable_http",
    host: "MCP Inspector",
    audience: "MCP Inspector reviewers validating tools/list, resources/list, prompts/list, and first cart flow.",
  }),
  hostFastPath({
    source: "github_copilot",
    target: "cursor_windsurf_vscode",
    host: "GitHub Copilot",
    audience: "Copilot and IDE-agent users validating Packrift as a remote MCP server from developer workflows.",
  }),
  hostFastPath({
    source: "gemini_remote_mcp",
    target: "generic_streamable_http",
    host: "Gemini",
    audience: "Gemini and Google AI agent workflows that can mount a remote Streamable HTTP MCP endpoint.",
  }),
  hostFastPath({
    source: "smithery",
    target: "generic_streamable_http",
    host: "Smithery",
    audience: "Smithery users and reviewers validating the hosted Packrift MCP endpoint.",
  }),
  hostFastPath({
    source: "browser_agent_bridge",
    target: "generic_streamable_http",
    host: "Browser agents",
    audience: "browser-use, Playwright, CUA, and other browser-agent workflows that need a bridge back to live MCP tools.",
  }),
  hostFastPath({
    source: "vercel_agent",
    target: "generic_streamable_http",
    host: "Vercel agents",
    audience: "Vercel, v0, and web-app agent builders wiring Packrift into commerce workflows.",
  }),
  hostFastPath({
    source: "crewai_agent",
    target: "generic_streamable_http",
    host: "CrewAI",
    audience: "CrewAI procurement or fulfillment agents that need exact SKU lookup, live checks, and measured cart handoff.",
  }),
  hostFastPath({
    source: "autogen_agent",
    target: "generic_streamable_http",
    host: "AutoGen",
    audience: "AutoGen multi-agent workflows that need a no-auth remote MCP commerce tool.",
  }),
  hostFastPath({
    source: "semantic_kernel_agent",
    target: "generic_streamable_http",
    host: "Semantic Kernel",
    audience: "Semantic Kernel agent workflows that need exact-spec packaging procurement tools.",
  }),
  hostFastPath({
    source: "pydantic_ai_agent",
    target: "generic_streamable_http",
    host: "Pydantic AI",
    audience: "Pydantic AI agents using Packrift MCP for typed exact-SKU search and cart handoff.",
  }),
  hostFastPath({
    source: "mastra_agent",
    target: "generic_streamable_http",
    host: "Mastra",
    audience: "Mastra agent workflows that can call remote MCP tools for packaging recommendations and cart URLs.",
  }),
  hostFastPath({
    source: "dify_agent",
    target: "generic_streamable_http",
    host: "Dify",
    audience: "Dify agent apps that need product search, live price, inventory, and measured cart handoff.",
  }),
  hostFastPath({
    source: "flowise_agent",
    target: "generic_streamable_http",
    host: "Flowise",
    audience: "Flowise agent builders wiring packaging procurement into flow-based automations.",
  }),
  hostFastPath({
    source: "langflow_agent",
    target: "generic_streamable_http",
    host: "Langflow",
    audience: "Langflow users building MCP-enabled commerce and procurement flows.",
  }),
  hostFastPath({
    source: "open_webui_agent",
    target: "generic_streamable_http",
    host: "Open WebUI",
    audience: "Open WebUI users adding Packrift as a remote MCP commerce server.",
  }),
  hostFastPath({
    source: "make_automation",
    target: "generic_streamable_http",
    host: "Make",
    audience: "Make automation builders creating packaging replenishment or procurement flows.",
  }),
  hostFastPath({
    source: "pipedream_automation",
    target: "generic_streamable_http",
    host: "Pipedream",
    audience: "Pipedream automation builders connecting Packrift MCP to ops workflows.",
  }),
  hostFastPath({
    source: "replit_agent",
    target: "generic_streamable_http",
    host: "Replit Agent",
    audience: "Replit users and agents adding Packrift MCP to generated apps or internal tools.",
  }),
  hostFastPath({
    source: "devin_agent",
    target: "generic_streamable_http",
    host: "Devin",
    audience: "Devin-style software agents validating Packrift MCP from implementation workflows.",
  }),
  hostFastPath({
    source: "goose_agent",
    target: "generic_streamable_http",
    host: "Goose",
    audience: "Goose users adding Packrift to local or remote MCP workflows.",
  }),
  hostFastPath({
    source: "sourcegraph_cody",
    target: "generic_streamable_http",
    host: "Sourcegraph Cody",
    audience: "Cody users validating a hosted Packrift MCP tool surface from developer environments.",
  }),
  hostFastPath({
    source: "aider_agent",
    target: "generic_streamable_http",
    host: "Aider",
    audience: "Aider users and coding-agent flows that need direct remote MCP access for Packrift examples.",
  }),
  hostFastPath({
    source: "msty_agent",
    target: "generic_streamable_http",
    host: "Msty",
    audience: "Msty users adding Packrift as an MCP-backed commerce and product-search tool.",
  }),
  hostFastPath({
    source: "lmstudio_agent",
    target: "generic_streamable_http",
    host: "LM Studio",
    audience: "LM Studio local-agent workflows calling Packrift through remote MCP.",
  }),
  hostFastPath({
    source: "ollama_agent",
    target: "generic_streamable_http",
    host: "Ollama",
    audience: "Ollama-backed local agents that need hosted Packrift MCP tools.",
  }),
  hostFastPath({
    source: "anythingllm_agent",
    target: "generic_streamable_http",
    host: "AnythingLLM",
    audience: "AnythingLLM workspaces adding exact-spec Packrift procurement tools through MCP.",
  }),
  hostFastPath({
    source: "jan_agent",
    target: "generic_streamable_http",
    host: "Jan",
    audience: "Jan local-agent users validating remote MCP tools for commerce workflows.",
  }),
  hostFastPath({
    source: "lovable_agent",
    target: "generic_streamable_http",
    host: "Lovable",
    audience: "Lovable app-building agents that need Packrift product and cart handoff examples.",
  }),
  hostFastPath({
    source: "manus_agent",
    target: "generic_streamable_http",
    host: "Manus",
    audience: "Manus-style general agents using Packrift as a live commerce tool.",
  }),
  hostFastPath({
    source: "official_registry",
    target: "generic_streamable_http",
    host: "Official MCP Registry",
    audience: "Official registry reviewers and downstream clients that ingest registry metadata.",
  }),
  hostFastPath({
    source: "mcpservers_org",
    target: "generic_streamable_http",
    host: "mcpservers.org",
    audience: "mcpservers.org users and recrawl reviewers validating the hosted Packrift server.",
  }),
  hostFastPath({
    source: "mcp_directory",
    target: "generic_streamable_http",
    host: "MCP Directory",
    audience: "mcp.directory reviewers and users checking Packrift after submission.",
  }),
  hostFastPath({
    source: "anthropic_connectors_directory",
    target: "claude_code",
    host: "Anthropic Connectors Directory",
    audience: "Claude connector reviewers validating a no-auth hosted Packrift MCP server.",
  }),
  hostFastPath({
    source: "mcp_marketplace_io",
    target: "mcp_marketplace",
    host: "MCP Marketplace",
    audience: "MCP Marketplace users and reviewers validating the Packrift marketplace listing.",
  }),
  hostFastPath({
    source: "mcpbench",
    target: "generic_streamable_http",
    host: "MCPBench",
    audience: "MCPBench crawlers, benchmark reviewers, and downstream users ingesting registry entries.",
  }),
  hostFastPath({
    source: "mcpfinder",
    target: "generic_streamable_http",
    host: "MCPfinder",
    audience: "MCPfinder reviewers and users validating Packrift after directory submission.",
  }),
  hostFastPath({
    source: "findmcp_dev",
    target: "generic_streamable_http",
    host: "FindMCP",
    audience: "FindMCP users and maintainers who need a source-aware Packrift proof path.",
  }),
  hostFastPath({
    source: "mcplist_ai",
    target: "generic_streamable_http",
    host: "MCPList.ai",
    audience: "MCPList.ai maintainers and users validating the hosted endpoint.",
  }),
  hostFastPath({
    source: "mcphubz",
    target: "generic_streamable_http",
    host: "MCPHubz",
    audience: "MCPHubz reviewers and users checking Packrift after submission.",
  }),
  hostFastPath({
    source: "mcplane",
    target: "generic_streamable_http",
    host: "MCPLane",
    audience: "MCPLane reviewers and users needing source-aware proof that the hosted MCP endpoint works.",
  }),
  hostFastPath({
    source: "mcpsolutions_dev",
    target: "generic_streamable_http",
    host: "MCP Solutions",
    audience: "MCP Solutions reviewers and users validating Packrift after basic listing submission.",
  }),
  hostFastPath({
    source: "gpmcp",
    target: "generic_streamable_http",
    host: "GPMCP",
    audience: "GPMCP maintainers and users evaluating Packrift for inclusion.",
  }),
  hostFastPath({
    source: "theresamcpforthat",
    target: "generic_streamable_http",
    host: "There's An MCP For That",
    audience: "Directory users and maintainers checking whether Packrift is the packaging procurement MCP.",
  }),
  hostFastPath({
    source: "mcpserverfinder",
    target: "generic_streamable_http",
    host: "MCP Server Finder",
    audience: "MCP Server Finder maintainers and users validating Packrift after outreach.",
  }),
  hostFastPath({
    source: "mcpserver_cc",
    target: "generic_streamable_http",
    host: "mcpserver.cc",
    audience: "mcpserver.cc reviewers and users validating the public Packrift submission.",
  }),
  hostFastPath({
    source: "mcpserverspot",
    target: "generic_streamable_http",
    host: "MCP Server Spot",
    audience: "MCP Server Spot reviewers and users validating Packrift after form submission.",
  }),
  hostFastPath({
    source: "mcpskills",
    target: "generic_streamable_http",
    host: "MCPSkills",
    audience: "MCPSkills reviewers and users checking Packrift publication status.",
  }),
  hostFastPath({
    source: "agentndx",
    target: "generic_streamable_http",
    host: "AgentNDX",
    audience: "AgentNDX reviewers and users validating Packrift after direct submission.",
  }),
  hostFastPath({
    source: "mcpcentral",
    target: "generic_streamable_http",
    host: "MCP Central",
    audience: "MCP Central reviewers and users validating Packrift through source-aware proof links.",
  }),
  hostFastPath({
    source: "mcpmarket_com",
    target: "mcp_marketplace",
    host: "MCPMarket",
    audience: "MCPMarket reviewers and users validating Packrift through marketplace-style install flows.",
  }),
  hostFastPath({
    source: "pulsemcp_packrift",
    target: "generic_streamable_http",
    host: "PulseMCP",
    audience: "PulseMCP crawlers and users ingesting Packrift from the official registry or public server metadata.",
  }),
  hostFastPath({
    source: "chiark",
    target: "generic_streamable_http",
    host: "Chiark",
    audience: "Chiark crawlers and users validating Packrift through upstream MCP registry coverage.",
  }),
];

export function allAgentCapturePayload(runtime: AgentCaptureRuntime) {
  const surfaces = [
    surface({
      id: "hosted_mcp_endpoint",
      name: "Packrift hosted MCP endpoint",
      agent_type: "remote_mcp",
      audience: "Any MCP-capable agent, including ChatGPT, Claude, Cursor, Windsurf, Codex, and VS Code clients.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: MCP_ENDPOINT,
      install_or_call:
        "Add a remote Streamable HTTP MCP server named packrift at https://mcp.packrift.com/mcp. For source-aware installs, use one of the agent_host_fast_paths entries so the first run credits the right agent host.",
      proof_url: "https://mcp.packrift.com/health",
      fallback_url: "https://mcp.packrift.com/manifest",
      next_action: "Keep tools/list, resources/list, prompts/list, health, and cart handoff smoke checks green.",
    }),
    surface({
      id: "mcp_start",
      name: "Packrift MCP start page",
      agent_type: "developer_onboarding",
      audience: "Agents, developers, directory reviewers, and AI-commerce operators who need one URL for install, first test, and measured cart handoff.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/start",
      install_or_call:
        "Open the start page or read /ai/mcp-start.json for remote MCP config, Claude/Codex install commands, first-flow JSON-RPC calls, buyer prompts, proof URLs, /r/start/{source} tracked start links, and /r/config/{source} tracked config links.",
      proof_url: "https://mcp.packrift.com/ai/mcp-start.json",
      fallback_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      next_action: "Use source-specific /r/start/{source} and /r/config/{source} links as the shortest public install paths in directory recrawls and external agent handoffs.",
    }),
    surface({
      id: "mcp_adoption_kit",
      name: "Packrift MCP adoption kit",
      agent_type: "developer_onboarding",
      audience: "Developers, agent builders, marketplaces, and AI-commerce workflows that need a quick install and first useful test.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      install_or_call:
        "Use the hosted adoption kit for remote MCP config, Claude/Codex install commands, first-five-minute JSON-RPC calls, curl/JavaScript/Python examples, demo SKUs, and exact-match rules.",
      proof_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.md",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Use this as the primary handoff link for anyone trying Packrift MCP for the first time.",
    }),
    surface({
      id: "mcp_agent_host_rollout",
      name: "Packrift MCP agent host rollout",
      agent_type: "runtime_source_capture",
      audience: "Agent builders and operators wiring Packrift MCP into recognizable hosts such as Cline, Cursor, Windsurf, Codex, Claude, OpenAI/ChatGPT, Vercel, LangChain, LlamaIndex, CrewAI, AutoGen, n8n, Zapier, Dify, Flowise, Docker, MCP.so, MCP Inspector, Goose, Sourcegraph Cody, Aider, Msty, LM Studio, Ollama, AnythingLLM, Lovable, Manus, and major MCP directories.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.json",
      install_or_call:
        "Use the rollout sheet to pick the source slug for a host family, copy the source-aware endpoint, and share tracked install, first-run, activation, and eval links without creating a duplicate Packrift CLI.",
      proof_url: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-install-matrix.json",
      next_action:
        "Use this as the fast all-agent rollout sheet when a new host, framework, automation tool, or directory needs source-aware Packrift MCP links.",
    }),
    surface({
      id: "mcp_install_matrix",
      name: "Packrift MCP install matrix",
      agent_type: "developer_onboarding",
      audience: "Agent hosts, developers, directories, and AI-commerce builders that need copy-ready remote MCP setup for common clients.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-install-matrix.json",
      install_or_call:
        "Use the install matrix for generic remote MCP JSON, mcp-remote stdio bridge, Claude, Codex, IDE-host, Glama, marketplace, browser-agent, and optional container install paths plus smoke-test JSON-RPC calls.",
      proof_url: "https://mcp.packrift.com/ai/mcp-install-matrix.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      next_action: "Use this as the copy-ready setup layer when asking agent platforms, directories, and developers to try Packrift MCP.",
    }),
    surface({
      id: "mcp_install_actions",
      name: "Packrift MCP tracked install actions",
      agent_type: "developer_onboarding",
      audience: "Directories, partner handoffs, and agent hosts that need one target-specific install URL with source attribution.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-install-actions.json",
      install_or_call:
        "Use /r/install/{source}/{target} for generic MCP JSON, stdio_mcp_remote bridge config, Claude Code, Codex, Claude Desktop, IDE hosts, Glama, and marketplace install handoffs that count as install intent.",
      proof_url: "https://mcp.packrift.com/ai/mcp-install-actions.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-install-matrix.json",
      next_action: "Use tracked install actions when a directory or partner can link directly to a client-specific setup path.",
    }),
    surface({
      id: "mcp_first_run_actions",
      name: "Packrift MCP tracked first-run actions",
      agent_type: "developer_activation",
      audience: "Directories, reviewers, partners, and agent hosts that have installed Packrift MCP and need a one-click path into a measurable first useful run.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-first-run-actions.json",
      install_or_call:
        "Use /r/run/{source}/{target} after install to return a source-aware endpoint, JSON-RPC sequence, curl script, and shell one-liner that reaches create_cart_url without placing an order.",
      proof_url: "https://mcp.packrift.com/ai/mcp-first-run-actions.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-install-actions.json",
      next_action: "Use tracked first-run actions to move listed sources from config/install intent into real tools/list, live checks, and create_cart_url usage.",
    }),
    surface({
      id: "mcp_reviewer_activation",
      name: "Packrift MCP reviewer activation",
      agent_type: "reviewer_activation",
      audience: "Directory reviewers, agent hosts, and partners who clicked proof links but need a real MCP client sequence ending in measured cart handoff.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-reviewer-activation.json",
      install_or_call:
        "Use /r/activate/{source}?format=html after proof clicks to install the hosted MCP endpoint in the browser, run the source-aware JSON-RPC sequence, and require create_cart_url to return an MCP /r/cart URL.",
      proof_url: "https://mcp.packrift.com/ai/mcp-reviewer-activation.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-first-run-actions.json",
      next_action: "Use this handoff for sources that show install or first-run proof interest but have not produced real MCP tool calls or cart URLs.",
    }),
    surface({
      id: "mcp_client_config",
      name: "Packrift MCP client config",
      agent_type: "developer_onboarding",
      audience: "Agent hosts, IDEs, directory reviewers, and developers that need the smallest copy-ready MCP JSON config.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-client-config.json",
      install_or_call:
        "Fetch /mcp.json, /.well-known/mcp.json, /ai/mcp-client-config.json, or /r/config/{source} and install the mcpServers.packrift remote HTTP endpoint; use the stdio_mcp_remote mcp-remote bridge only for hosts that cannot call remote HTTP directly.",
      proof_url: "https://mcp.packrift.com/ai/mcp-client-config.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-install-matrix.json",
      next_action: "Use this as the shortest config file in directory submissions and IDE agent setup docs.",
    }),
    surface({
      id: "agent_web_manifest_and_capability_card",
      name: "Agent Web manifest and capability card",
      agent_type: "agent_discovery_manifest",
      audience: "Agent crawlers, capability indexes, commerce-agent directories, and source registries that probe well-known agent metadata before MCP-specific cards.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/.well-known/agent.json",
      install_or_call:
        "Fetch /.well-known/agent.json for Packrift's action-level agent manifest, then fetch /.well-known/capability-card.json for the compact protocol, endpoint, use-case, and order-safety card.",
      proof_url: "https://mcp.packrift.com/.well-known/capability-card.json",
      fallback_url: "https://mcp.packrift.com/.well-known/mcp/server-card.json",
      next_action:
        "Keep both well-known manifests in llms.txt, llms-full.txt, server cards, resources/list, cache purges, and distribution checks so generic agent crawlers can discover the hosted MCP endpoint.",
    }),
    surface({
      id: "mcp_usage_snapshot",
      name: "Packrift MCP usage snapshot",
      agent_type: "usage_measurement",
      audience: "Directory reviewers, agent builders, and Packrift operators who need public aggregate proof of MCP discovery, tool-call, and cart-handoff activity.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-usage-snapshot.json",
      install_or_call:
        "Use the public usage snapshot to verify first-party MCP discovery events, tool calls, create_cart_url calls, cart clicks, and proof-gate status by date.",
      proof_url: "https://mcp.packrift.com/ai/mcp-usage-snapshot.md",
      fallback_url: "https://mcp.packrift.com/events/ai-sales/summary",
      next_action: "Use this as the iteration proof layer while pushing installs and cart-handoff workflows toward measurable usage.",
    }),
    surface({
      id: "mcp_funnel_snapshot",
      name: "Packrift MCP funnel snapshot",
      agent_type: "funnel_measurement",
      audience: "Directory reviewers, agent builders, and Packrift operators who need the public proof gate from discovery to installs, cart landings, and order totals.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-funnel-snapshot.json",
      install_or_call:
        "Use the public funnel snapshot to verify aggregate starts, install intent, tool usage, qualified first-party MCP cart landings, and MCP-attributed order totals.",
      proof_url: "https://mcp.packrift.com/ai/mcp-funnel-snapshot.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-usage-snapshot.json",
      next_action: "Use this as the public goal gate; keep working until qualified visitors, cart landings, and MCP-attributed revenue are all proven.",
    }),
    surface({
      id: "mcp_ga4_funnel_proof",
      name: "Packrift MCP GA4 funnel proof",
      agent_type: "funnel_measurement",
      audience: "Directory reviewers, agent builders, and Packrift operators who need canonical visitor proof without local GA4 files or raw order rows.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-ga4-funnel-proof.json",
      install_or_call:
        "Use the public GA4 proof to verify qualified external MCP session starts, the remaining gap to 1,000 qualified visitors, qualified cart landings, and MCP-attributed order progress.",
      proof_url: "https://mcp.packrift.com/ai/mcp-ga4-funnel-proof.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-funnel-snapshot.json",
      next_action: "Treat this as the canonical visitor gate and keep proof-page fetches separate from buyer demand.",
    }),
    surface({
      id: "mcp_source_activation_queue",
      name: "Packrift MCP source activation queue",
      agent_type: "source_activation_measurement",
      audience: "Directory reviewers, agent hosts, partners, and Packrift operators deciding which source-specific MCP run should happen next.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-source-activation-queue.json",
      install_or_call:
        "Use the public queue or /r/activate command center to pick the next source-specific start, install, first-run, tool-call, cart-landing, or order event needed to move Packrift MCP toward measurable revenue.",
      proof_url: "https://mcp.packrift.com/ai/mcp-source-activation-queue.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-funnel-snapshot.json",
      next_action:
        "Open the command center, work critical rows first, and use the source-specific real MCP runner for sources with installs or create_cart_url output but missing tool calls, measured /r/cart landings, or orders.",
    }),
    surface({
      id: "mcp_visitor_growth_queue",
      name: "Packrift MCP visitor growth queue",
      agent_type: "distribution_and_growth_queue",
      audience: "Directory owners, agent hosts, browser-skill catalogs, partners, reviewers, and Packrift operators working the 1,000-qualified-session and order-proof gaps.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-visitor-growth-queue.json",
      install_or_call:
        "Use the visitor growth queue when the question is where to get more qualified Packrift MCP users next. It merges directory refreshes, source activation rows, agent-host links, and buyer handoffs into JSONL/CSV tasks while preserving the no-duplicate-work rule.",
      proof_url: "https://mcp.packrift.com/ai/mcp-visitor-growth-queue.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-agent-adoption-progress.json",
      next_action:
        "Work visitor-growth tasks that can send real external users to source-aware start/install links, then use mature buyer handoffs only when checkout review is approved.",
    }),
    surface({
      id: "mcp_revenue_conversion_queue",
      name: "Packrift MCP revenue conversion queue",
      agent_type: "revenue_conversion_measurement",
      audience: "Buyers, reviewers, agent hosts, and Packrift operators following up on mature MCP sources that already have tool-call and cart-landing proof.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.json",
      install_or_call:
        "Use the revenue conversion queue when a source row has moved past activation and needs a source-preserving buyer/reviewer handoff into Shopify checkout; the queue links buyer handoff pages, MCP /r/cart URLs, proof watches, and order-attribution requirements without creating synthetic order proof.",
      proof_url: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-source-activation-queue.json",
      next_action:
        "Work mature rows only: send the source-preserving cart handoff to a real buyer or reviewer, then watch GA4/Shopify funnel proof for first_party_mcp_orders or MCP revenue before counting the gate complete.",
    }),
    surface({
      id: "mcp_buyer_order_handoffs",
      name: "Packrift MCP buyer order handoffs",
      agent_type: "revenue_conversion_handoff",
      audience: "Real buyers, reviewers, procurement operators, and agent hosts who need a source-preserving checkout handoff for already-mature MCP sources.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.json",
      install_or_call:
        "Use this thin buyer/reviewer handoff hub when a source already has MCP tool-call and cart-landing proof. It points to existing /r/order/{source} and /r/cart handoffs, preserves MCP attribution, exposes JSONL/CSV checkout task exports, and never places an order.",
      proof_url: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.json",
      next_action:
        "Send the copy-ready buyer request to a real buyer or reviewer only when checkout evaluation is approved, then watch GA4/Shopify proof for MCP-attributed order or revenue.",
    }),
    surface({
      id: "mcp_activation_experiments",
      name: "Packrift MCP activation experiments",
      agent_type: "source_activation_measurement",
      audience: "Directory reviewers, agent hosts, partners, and Packrift operators who need source-specific hypotheses, target events, snapshot deltas, and suppression rules.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-activation-experiments.json",
      install_or_call:
        "Use the experiment board to run each source-specific MCP activation as a measurable test with tracked install URLs, first-run URLs, activation runners, copy-ready external requests, and proof-gate measurement links.",
      proof_url: "https://mcp.packrift.com/ai/mcp-activation-experiments.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-source-activation-queue.json",
      next_action:
        "Run critical experiments first and close them only when the linked usage, funnel, GA4, or source-queue snapshots show non-suppressed external proof.",
    }),
    surface({
      id: "mcp_external_activation_brief",
      name: "Packrift MCP selected external activation brief",
      agent_type: "external_activation_operations",
      audience:
        "External MCP directories, marketplace reviewers, agent-host operators, and Packrift operators who need the current smallest set of source-specific real MCP runs most likely to move the proof gates.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-external-activation-brief.json",
      install_or_call:
        "Use the selected task JSONL, CSV, or guarded shell runner to copy a source-aware install, run tools/list plus live product checks, and finish with create_cart_url from the real hosted MCP endpoint. This is a thin activation wrapper around https://mcp.packrift.com/mcp, not a separate Packrift CLI.",
      proof_url: "https://mcp.packrift.com/ai/mcp-external-activation-brief-tasks.jsonl",
      fallback_url: "https://mcp.packrift.com/ai/mcp-source-activation-queue.json",
      next_action:
        "Work the selected sources first, then watch mcp-agent-adoption-progress for external qualified MCP tool calls, GA4-qualified external sessions, and MCP-attributed orders.",
    }),
    surface({
      id: "buyer_mcp_use_cases",
      name: "Packrift MCP buyer use cases",
      agent_type: "buyer_workflow_corpus",
      audience: "AI shopping agents, procurement copilots, fulfillment teams, and answer engines evaluating buyer utility.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.json",
      install_or_call:
        "Use the buyer use-case map to route exact SKU reorder, fit-by-dimensions, mailer selection, label procurement, no-match quote recovery, and procurement line-item requests into MCP tools.",
      proof_url: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      next_action: "Keep this crawler-readable buyer workflow map aligned with MCP prompts, cart handoff candidates, and measured handoff URLs.",
    }),
    surface({
      id: "mcp_cart_activation",
      name: "Packrift MCP cart activation",
      agent_type: "conversion_activation",
      audience: "AI shopping agents, procurement copilots, and MCP directory reviewers that need the exact sequence from buyer intent to measured cart landing.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-cart-activation.json",
      install_or_call:
        "Use the cart activation playbook when an agent has exact buyer intent and needs the JSON-RPC sequence that creates a measured /r/cart landing after live checks.",
      proof_url: "https://mcp.packrift.com/ai/mcp-cart-activation.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.json",
      next_action:
        "Keep activation paths aligned with get_cart_handoff_candidates, create_cart_url, measured handoffs, and GA4 qualified cart-landing proof.",
    }),
    surface({
      id: "mcp_first_run_proof",
      name: "Packrift MCP first-run proof",
      agent_type: "developer_onboarding",
      audience: "External agents, developers, and directory reviewers that need one compact live proof of exact SKU, price, inventory, and measured cart handoff.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-first-run-proof.json",
      install_or_call:
        "Use the first-run proof to see a synthetic live SKU 1066 sequence, then run the same JSON-RPC calls against https://mcp.packrift.com/mcp.",
      proof_url: "https://mcp.packrift.com/ai/mcp-first-run-proof.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      next_action: "Use this as the shortest proof link for developers and directories before asking them to install or recrawl Packrift MCP.",
    }),
    surface({
      id: "mcp_workflow_gallery",
      name: "Packrift MCP workflow gallery",
      agent_type: "developer_onboarding",
      audience: "Agent hosts, developers, marketplaces, and AI-commerce builders that need copy-ready buyer prompts and JSON-RPC sequences.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-workflow-gallery.json",
      install_or_call:
        "Use the workflow gallery to turn exact SKU reorder, label reorder, literature mailer, fit-by-dimensions, and no-exact-match examples into host demos or evals.",
      proof_url: "https://mcp.packrift.com/ai/mcp-workflow-gallery.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      next_action: "Use this as the copy-ready workflow layer for agent platforms after the install matrix and first-run proof.",
    }),
    surface({
      id: "mcp_automation_workflows",
      name: "Packrift MCP automation workflows",
      agent_type: "automation_host_activation",
      audience: "n8n, Zapier, Pipedream, and similar automation builders who need importable real-MCP flows rather than another Packrift CLI.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-automation-workflows.json",
      install_or_call:
        "Import the n8n workflow JSON or copy the Zapier/Pipedream steps; each flow calls the hosted Packrift MCP endpoint, runs tools/list plus live price, inventory, cart-candidate, and create_cart_url requests, then records the measured /r/cart handoff without placing an order.",
      proof_url: "https://mcp.packrift.com/ai/mcp-automation-workflows.html",
      fallback_url: "https://mcp.packrift.com/ai/mcp-workflow-gallery.json",
      next_action:
        "Use this pack to move automation-host rows like n8n, Zapier, and Pipedream from proof-page reads into real external MCP tool calls and measured cart URLs.",
    }),
    surface({
      id: "mcp_eval_pack",
      name: "Packrift MCP eval pack",
      agent_type: "host_acceptance_test",
      audience: "MCP hosts, directories, marketplaces, and AI-commerce builders that need acceptance tests for a real Packrift MCP install.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-eval-pack.json",
      install_or_call:
        "Use the eval pack after install to run required tools/list, prompts/list, get_cart_handoff_candidates, get_pricing, check_inventory, and create_cart_url cases through the real MCP host without placing an order.",
      proof_url: "https://mcp.packrift.com/ai/mcp-eval-pack.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-first-run-actions.json",
      next_action: "Use this as the acceptance-test handoff for agent platforms that need real external tool-call and measured /r/cart proof beyond a browser page or static listing.",
    }),
    surface({
      id: "chatgpt_openai_product_cards",
      name: "ChatGPT and OpenAI product-card commerce",
      agent_type: "chat_commerce",
      audience: "OpenAI product and shopping agents that resolve exact products before purchase handoff.",
      status: "live",
      priority: "core",
      packrift_owned: false,
      canonical_url: "https://packrift.com",
      install_or_call:
        "Use the OpenAI-shaped product feed and Packrift MCP exact-spec records to resolve SKU, variant, price, inventory, and cart handoff.",
      proof_url: "https://mcp.packrift.com/ai/packrift-openai-products-strict-stable-current.tsv",
      fallback_url: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.json",
      next_action: "Keep paid ChatGPT SKU families mapped to MCP product records and measured cart routes.",
      notes: "Conversion-proven examples include SKUs 1066, MFL1295, and LL251WR.",
    }),
    surface({
      id: "shopify_native_ucp",
      name: "Shopify native UCP MCP",
      agent_type: "ucp_mcp",
      audience: "Agents that support Shopify UCP profile metadata and native Shopify catalog/cart behavior.",
      status: "ready",
      priority: "high",
      packrift_owned: false,
      canonical_url: "https://packrift.com/api/ucp/mcp",
      install_or_call:
        "Call only when the host agent sends a valid UCP profile at params.arguments.meta.ucp-agent.profile; otherwise use the Packrift exact-spec MCP first.",
      proof_url: "https://mcp.packrift.com/ai/shopify-native-ucp-commerce-surface.md",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Use UCP for Shopify-native behavior after exact SKU safety is established through Packrift MCP.",
    }),
    surface({
      id: "claude_desktop_and_claude_code",
      name: "Claude Desktop and Claude Code",
      agent_type: "remote_mcp_client",
      audience: "Claude users adding Packrift as a remote HTTP MCP server.",
      status: "ready",
      priority: "high",
      packrift_owned: false,
      canonical_url: sourceAwareEndpoint("claude_remote_mcp", "claude_code"),
      install_or_call:
        "claude mcp add --transport http packrift 'https://mcp.packrift.com/mcp?packrift_mcp_source=claude_remote_mcp&packrift_mcp_target=claude_code'",
      proof_url: "https://mcp.packrift.com/.well-known/mcp/server-card.json",
      fallback_url: "https://github.com/Packrift/packrift-mcp",
      next_action: "Keep Claude install snippets in llms-install.md, README, server card, and marketplace manifests consistent.",
    }),
    surface({
      id: "cursor_windsurf_vscode",
      name: "Cursor, Windsurf, and VS Code MCP clients",
      agent_type: "remote_mcp_client",
      audience: "IDE agents that read MCP JSON config or remote endpoint URLs.",
      status: "ready",
      priority: "high",
      packrift_owned: false,
      canonical_url: sourceAwareEndpoint("cursor_directory", "cursor_windsurf_vscode"),
      install_or_call:
        "{\"mcpServers\":{\"packrift\":{\"type\":\"http\",\"url\":\"https://mcp.packrift.com/mcp?packrift_mcp_source=cursor_directory&packrift_mcp_target=cursor_windsurf_vscode\"}}}",
      proof_url: "https://mcp.packrift.com/manifest",
      fallback_url: "https://mcp.packrift.com/resources",
      next_action: "Keep the config snippet minimal so IDE agents do not self-host unless they need local development.",
    }),
    surface({
      id: "codex_remote_mcp",
      name: "Codex remote MCP",
      agent_type: "remote_mcp_client",
      audience: "Codex workspaces that should use the current hosted endpoint instead of a duplicate CLI.",
      status: "ready",
      priority: "high",
      packrift_owned: false,
      canonical_url: sourceAwareEndpoint("codex_remote_mcp", "codex"),
      install_or_call:
        "codex mcp add packrift --url 'https://mcp.packrift.com/mcp?packrift_mcp_source=codex_remote_mcp&packrift_mcp_target=codex'",
      proof_url: "https://mcp.packrift.com/ai/packrift-ai-agent-instructions.md",
      fallback_url: "https://github.com/Packrift/packrift-mcp",
      next_action: "Keep this as a thin remote endpoint install path; do not fork a separate Packrift CLI surface.",
    }),
    surface({
      id: "glama_hosted_connector",
      name: "Glama hosted connector",
      agent_type: "mcp_connector_directory",
      audience: "Agents and users who prefer a hosted MCP connector directory install.",
      status: "monitored",
      priority: "high",
      packrift_owned: false,
      canonical_url: "https://glama.ai/mcp/connectors/io.github.Packrift/packrift-mcp",
      install_or_call: "Install Packrift from the Glama hosted connector and confirm the hosted endpoint remains healthy.",
      proof_url: "https://mcp.packrift.com/.well-known/glama.json",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Distribution check must keep Glama healthy with all current tools visible.",
    }),
    surface({
      id: "official_mcp_registry",
      name: "Official MCP Registry",
      agent_type: "mcp_registry",
      audience: "MCP clients and downstream directories that ingest the official registry.",
      status: "monitored",
      priority: "core",
      packrift_owned: false,
      canonical_url: "https://registry.modelcontextprotocol.io/v0/servers?search=Packrift",
      install_or_call: "Resolve io.github.Packrift/packrift-mcp and use the remote https://mcp.packrift.com/mcp transport.",
      proof_url: "https://mcp.packrift.com/server-card.json",
      fallback_url: "https://github.com/Packrift/packrift-mcp/blob/main/server.json",
      next_action: "Republish server.json whenever the public MCP surface changes.",
    }),
    surface({
      id: "mcp_marketplace",
      name: "MCP Marketplace",
      agent_type: "mcp_directory",
      audience: "Agents browsing MCP servers through marketplace-style discovery.",
      status: "monitored",
      priority: "medium",
      packrift_owned: false,
      canonical_url: "https://mcp-marketplace.io/server/io-github-packrift-packrift-mcp",
      install_or_call: "Use the public marketplace listing, then call the hosted Packrift MCP endpoint.",
      proof_url: "https://mcp.packrift.com/.well-known/mcp-marketplace.json",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Keep marketplace discovery manifest aligned with server card, tool count, and launch guide.",
    }),
    surface({
      id: "github_source_and_container",
      name: "GitHub source and GHCR container",
      agent_type: "source_package",
      audience: "Directories and local environments that require a package or container install surface.",
      status: "ready",
      priority: "medium",
      packrift_owned: true,
      canonical_url: "https://github.com/Packrift/packrift-mcp",
      install_or_call: "docker pull ghcr.io/packrift/packrift-mcp:latest",
      proof_url: "https://github.com/Packrift/packrift-mcp/blob/main/server.json",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Keep the hosted endpoint primary; use the container only where package-style installation is required.",
    }),
    surface({
      id: "llms_txt_and_full_corpus",
      name: "llms.txt and llms-full.txt",
      agent_type: "crawler_corpus",
      audience: "Search, answer, and shopping agents that crawl public text files before tool calling.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/llms.txt",
      install_or_call: "Fetch llms.txt first, then llms-full.txt for dense exact-spec Packrift context.",
      proof_url: "https://mcp.packrift.com/llms-full.txt",
      fallback_url: "https://mcp.packrift.com/ai/sitemap.xml",
      next_action: "Keep static availability checks green across crawler user agents.",
    }),
    surface({
      id: "root_agents_md",
      name: "Root agents.md",
      agent_type: "crawler_instruction",
      audience: "Agents that look for root-domain instructions before crawling product or tool surfaces.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://packrift.com/agents.md",
      install_or_call: "Read root-domain agent instructions, then use the Packrift MCP endpoint for live facts.",
      proof_url: "https://mcp.packrift.com/ai/packrift-ai-agent-instructions.md",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Keep the Shopify-root route and MCP-hosted copy consistent.",
    }),
    surface({
      id: "ai_product_corpus",
      name: "AI-approved product corpus",
      agent_type: "structured_catalog",
      audience: "Offline indexing agents, retrieval systems, and shopping agents that need exact SKU/spec records.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/packrift-ai-approved-products.jsonl",
      install_or_call: "Index only AI_APPROVE rows and preserve SKU, variant, family, dimensions, pack count, product URL, and no-match rules.",
      proof_url: "https://mcp.packrift.com/ai/all-ai-approved-sku-sitemap.xml",
      fallback_url: "https://mcp.packrift.com/ai/purchase-paths.jsonl",
      next_action: "Refresh product corpus through the existing approved-catalog pipeline rather than editing rows by hand.",
    }),
    surface({
      id: "measured_handoff_directory",
      name: "Measured handoff directory",
      agent_type: "conversion_handoff",
      audience: "Agents that can recommend a product but need a safe measured buyer handoff path.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/measured-handoffs.json",
      install_or_call: "Use measured product, reorder, quote, cart, SKU markdown, SKU JSON, and copy-procurement-spec routes after live MCP confirmation.",
      proof_url: "https://mcp.packrift.com/ai/measured-handoffs.md",
      fallback_url: "https://mcp.packrift.com/ai/conversion-route-catalog.json",
      next_action: "Keep route telemetry and cart smoke checks tied to priority exact-spec SKUs.",
    }),
    surface({
      id: "cart_handoff_candidates",
      name: "MCP cart handoff candidates",
      agent_type: "tool_callable_cart",
      audience: "Agents that need ready create_cart_url arguments for priority exact SKUs.",
      status: "live",
      priority: "core",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.json",
      install_or_call: "Call get_cart_handoff_candidates, then get_product, get_pricing, check_inventory, and create_cart_url only after exact SKU and quantity are confirmed.",
      proof_url: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.md",
      fallback_url: "https://mcp.packrift.com/ai/crawler-safe-purchase-paths.md",
      next_action: "Keep synthetic cart checks on 1066, LL251WR, and MFL1295 passing.",
    }),
    surface({
      id: "browser_agent_bridge",
      name: "Browser-agent bridge",
      agent_type: "browser_agent_bridge",
      audience: "Browserbase Browse-style, browser-use, Playwright, CUA, and other browser agents that can read URLs but may not install MCP directly.",
      status: "live",
      priority: "high",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/browser-agent-bridge.json",
      install_or_call:
        "Read the browser-agent bridge, crawl public Packrift resources for discovery, then route live price, inventory, shipping, and cart handoff through https://mcp.packrift.com/mcp?packrift_mcp_source=browser_agent_bridge&packrift_mcp_target=generic_streamable_http.",
      proof_url: "https://mcp.packrift.com/ai/browser-agent-bridge.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
      next_action: "Track browser-agent bridge fetches as discovery reads and only count them as qualified demand after MCP tool use or stamped cart progression.",
    }),
    surface({
      id: "browserbase_browse_candidate",
      name: "Browserbase Browse / browse.sh",
      agent_type: "browser_skill_catalog",
      audience: "Browser agents that install open-web skills and use browser primitives for dynamic sites.",
      status: "live",
      priority: "high",
      packrift_owned: false,
      canonical_url: "https://browse.sh/",
      install_or_call:
        "Install with browse skills add packrift.com/exact-spec-packaging-procurement-e4ujmy. The skill is verified, recommended_method=mcp, and routes live facts through https://mcp.packrift.com/mcp?packrift_mcp_source=browse_sh&packrift_mcp_target=generic_streamable_http.",
      proof_url: "https://mcp.packrift.com/SKILL.md",
      fallback_url: "https://mcp.packrift.com/mcp",
      next_action: "Monitor Browse install count and skill quality; keep all Browse usage routed through the hosted MCP endpoint.",
      notes:
        "Browse is useful as an agent browser-skill pattern; Packrift's current canonical agent surface remains MCP plus corpus. Browse accepted the Add website submission on 2026-05-19, browse skills find packrift returns a verified skill, and browse skills add installed it locally.",
    }),
    surface({
      id: "mcp_directory_refreshes",
      name: "Secondary MCP directory refreshes",
      agent_type: "mcp_directory",
      audience: "MCPBench, mcpservers.org, mcp.directory, PulseMCP, Chiark, Docker MCP Catalog, and other secondary discovery surfaces.",
      status: "monitored",
      priority: "high",
      packrift_owned: false,
      canonical_url: "https://mcp.packrift.com/ai/mcp-directory-refresh.json",
      install_or_call: "Use the public directory refresh pack plus server.json, server card, live health, resources/list, tools/list, prompts/list, and cart-handoff evidence.",
      proof_url: "https://mcp.packrift.com/ai/mcp-directory-refresh.md",
      fallback_url: "https://mcp.packrift.com/ai/all-agent-capture.json",
      next_action: "Push stale directory refreshes from this public recrawl pack instead of creating separate Packrift surfaces.",
    }),
    surface({
      id: "mcp_directory_submit_actions",
      name: "MCP directory submit actions",
      agent_type: "mcp_directory_operations",
      audience: "Directory support teams, listing reviewers, and Packrift operators turning stale discovery surfaces into current listings.",
      status: "live",
      priority: "high",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/mcp-directory-submit-actions.json",
      install_or_call:
        "Use the public submit-action queue for per-directory status, proof URLs, tracked start URLs, and copy-ready recrawl messages.",
      proof_url: "https://mcp.packrift.com/ai/mcp-directory-submit-actions.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-directory-refresh.json",
      next_action:
        "Use this to keep mcpservers.org, MCP.Directory, Claude Connectors Directory, Smithery, Cline MCP Marketplace, MCP.so, MCP Market, Cursor Directory, MCP Central, MCPfinder, Glama source listing, PulseMCP, MCPBench, Chiark, and Docker MCP Catalog moving with tracked start /r/start/{source} links and current proof.",
    }),
    surface({
      id: "agent_capture_outreach_packet",
      name: "Packrift agent capture outreach packet",
      agent_type: "distribution_operations",
      audience: "Agent hosts, directory reviewers, partners, support teams, and Packrift operators who need one combined packet for install snippets, proof links, tracked directory URLs, and copy-ready recrawl messages.",
      status: "live",
      priority: "high",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/agent-capture-outreach.json",
      install_or_call:
        "Use the outreach packet as the single public distribution handoff: it combines all-agent capture, directory submit actions, tracked start/config URLs, Claude/Codex/Cursor install snippets, Browserbase Browse catalog guidance, and copy-ready recrawl messages.",
      proof_url: "https://mcp.packrift.com/ai/agent-capture-outreach.html",
      fallback_url: "https://mcp.packrift.com/ai/agent-capture-outreach.md",
      next_action:
        "Use this packet when pushing stale directories, agent platforms, partners, and Browse-style agents toward the canonical hosted MCP endpoint.",
    }),
    surface({
      id: "claude_connector_submission_packet",
      name: "Claude connector submission packet",
      agent_type: "mcp_directory_operations",
      audience: "Claude Connectors Directory reviewers and the Packrift operator submitting the hosted MCP server for Claude discovery.",
      status: "ready",
      priority: "high",
      packrift_owned: true,
      canonical_url: "https://mcp.packrift.com/ai/claude-connector-submission.json",
      install_or_call:
        "Use the packet for form-ready fields, no-auth endpoint proof, legal/support URLs, allowed redirect hosts, tracked Claude start/config URLs, and buyer safety rules.",
      proof_url: "https://mcp.packrift.com/ai/claude-connector-submission.md",
      fallback_url: "https://mcp.packrift.com/ai/mcp-directory-submit-actions.json",
      next_action:
        "Submit Packrift MCP through the Claude connector submission form using the source-attributed start/config links and public proof URLs in this packet.",
    }),
    surface({
      id: "search_and_answer_crawlers",
      name: "Search and answer-engine crawlers",
      agent_type: "crawler",
      audience: "Google, Bing, Perplexity-style, Gemini-style, and answer-engine crawlers that discover structured commerce pages.",
      status: "ready",
      priority: "high",
      packrift_owned: false,
      canonical_url: "https://mcp.packrift.com/sitemap.xml",
      install_or_call: "Crawl sitemaps, llms files, per-SKU pages, product corpus, and measured handoff directories.",
      proof_url: "https://mcp.packrift.com/robots.txt",
      fallback_url: "https://packrift.com/sitemap.xml",
      next_action: "Keep public sitemaps, root agents.md, IndexNow, and AI corpus files in sync.",
    }),
  ];

  const generatedAt = new Date().toISOString();
  return {
    release: "PACKRIFT-ALL-AGENT-CAPTURE-R31",
    generated_at: generatedAt,
    status: "canonical_current_mcp_capture_layer",
    owner: "Packrift",
    canonical_endpoint: MCP_ENDPOINT,
    agent_host_fast_paths_release: "PACKRIFT-AGENT-HOST-FAST-PATHS-R03",
    agent_host_fast_paths: AGENT_HOST_FAST_PATHS,
    hub_urls: {
      json: "https://mcp.packrift.com/ai/all-agent-capture.json",
      markdown: "https://mcp.packrift.com/ai/all-agent-capture.md",
      start: "https://mcp.packrift.com/start",
      start_json: "https://mcp.packrift.com/ai/mcp-start.json",
      agent_instructions: "https://mcp.packrift.com/ai/packrift-ai-agent-instructions.md",
      usage_snapshot: "https://mcp.packrift.com/ai/mcp-usage-snapshot.json",
      funnel_snapshot: "https://mcp.packrift.com/ai/mcp-funnel-snapshot.json",
      ga4_funnel_proof: "https://mcp.packrift.com/ai/mcp-ga4-funnel-proof.json",
      source_activation_queue: "https://mcp.packrift.com/ai/mcp-source-activation-queue.json",
      source_activation_queue_html: "https://mcp.packrift.com/ai/mcp-source-activation-queue.html",
      visitor_growth_queue: "https://mcp.packrift.com/ai/mcp-visitor-growth-queue.json",
      visitor_growth_queue_html: "https://mcp.packrift.com/ai/mcp-visitor-growth-queue.html",
      visitor_growth_tasks_jsonl: "https://mcp.packrift.com/ai/mcp-visitor-growth-tasks.jsonl",
      visitor_growth_tasks_csv: "https://mcp.packrift.com/ai/mcp-visitor-growth-tasks.csv",
      revenue_conversion_queue: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.json",
      revenue_conversion_queue_html: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.html",
      buyer_order_handoffs: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.json",
      buyer_order_handoffs_html: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.html",
      buyer_order_handoffs_tasks_jsonl: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs-tasks.jsonl",
      buyer_order_handoffs_tasks_csv: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs-tasks.csv",
      agent_host_rollout: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.json",
      agent_host_rollout_html: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.html",
      agent_host_rollout_tasks_jsonl: "https://mcp.packrift.com/ai/mcp-agent-host-rollout-tasks.jsonl",
      agent_host_rollout_tasks_csv: "https://mcp.packrift.com/ai/mcp-agent-host-rollout-tasks.csv",
      activation_experiments: "https://mcp.packrift.com/ai/mcp-activation-experiments.json",
      activation_experiments_html: "https://mcp.packrift.com/ai/mcp-activation-experiments.html",
      external_activation_brief: "https://mcp.packrift.com/ai/mcp-external-activation-brief.json",
      external_activation_brief_html: "https://mcp.packrift.com/ai/mcp-external-activation-brief.html",
      external_activation_brief_tasks_jsonl: "https://mcp.packrift.com/ai/mcp-external-activation-brief-tasks.jsonl",
      external_activation_brief_tasks_csv: "https://mcp.packrift.com/ai/mcp-external-activation-brief-tasks.csv",
      external_activation_brief_runner_shell: "https://mcp.packrift.com/ai/mcp-external-activation-brief-runner.sh",
      activation_command_center: "https://mcp.packrift.com/r/activate",
      install_matrix: "https://mcp.packrift.com/ai/mcp-install-matrix.json",
      first_run_actions: "https://mcp.packrift.com/ai/mcp-first-run-actions.json",
      reviewer_activation: "https://mcp.packrift.com/ai/mcp-reviewer-activation.json",
      tracked_reviewer_activation_generic: "https://mcp.packrift.com/r/activate/generic",
      tracked_reviewer_activation_runner_generic: "https://mcp.packrift.com/r/activate/generic?format=html",
      tracked_reviewer_activation_shell_runner_generic: "https://mcp.packrift.com/r/activate/generic?format=sh",
      client_config: "https://mcp.packrift.com/ai/mcp-client-config.json",
      tracked_config_generic: "https://mcp.packrift.com/r/config/generic",
      root_mcp_json: "https://mcp.packrift.com/mcp.json",
      well_known_mcp_json: "https://mcp.packrift.com/.well-known/mcp.json",
      agent_web_manifest: "https://mcp.packrift.com/.well-known/agent.json",
      root_agent_web_manifest: "https://mcp.packrift.com/agent.json",
      capability_card: "https://mcp.packrift.com/.well-known/capability-card.json",
      buyer_use_cases: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.json",
      cart_activation: "https://mcp.packrift.com/ai/mcp-cart-activation.json",
      first_run_proof: "https://mcp.packrift.com/ai/mcp-first-run-proof.json",
      workflow_gallery: "https://mcp.packrift.com/ai/mcp-workflow-gallery.json",
      automation_workflows: "https://mcp.packrift.com/ai/mcp-automation-workflows.json",
      n8n_workflow_import: "https://mcp.packrift.com/ai/mcp-n8n-workflow.json",
      eval_pack: "https://mcp.packrift.com/ai/mcp-eval-pack.json",
      browser_agent_bridge: "https://mcp.packrift.com/ai/browser-agent-bridge.json",
      directory_refresh: "https://mcp.packrift.com/ai/mcp-directory-refresh.json",
      claude_connector_submission: "https://mcp.packrift.com/ai/claude-connector-submission.json",
      agent_capture_outreach: "https://mcp.packrift.com/ai/agent-capture-outreach.json",
      llms: "https://mcp.packrift.com/llms.txt",
      server_card: "https://mcp.packrift.com/.well-known/mcp/server-card.json",
    },
    runtime: {
      server_version: runtime.serverVersion,
      tools_count: runtime.toolsCount,
      resources_count: runtime.resourcesCount,
      prompts_count: runtime.promptsCount,
    },
    operating_rules: [
      "Use the current hosted Packrift MCP endpoint as the canonical agent surface.",
      "Do not create a separate Packrift CLI or duplicate buyer interface unless it is only a thin wrapper around the hosted MCP endpoint.",
      "Use exact AI_APPROVE SKU/spec matching before product, reorder, quote, or cart handoff.",
      "Confirm live price, inventory, shipping, and cart eligibility through MCP tools before presenting a cart or checkout action.",
      "When create_cart_url returns an MCP /r/cart landing URL, use that as the primary buyer handoff so cart progression is measurable before Shopify checkout.",
      "When an external directory is stale or blocked, refresh that directory with this matrix, server.json, health, resources/list, tools/list, and cart smoke evidence.",
      "Use /r/config/{source} for tracked config fetches when a directory or host accepts a direct MCP JSON config URL.",
      "Use /.well-known/agent.json and /.well-known/capability-card.json for generic agent-web and capability-index crawlers that probe well-known manifests before MCP resources/list.",
      "Use /r/install/{source}/{target} for tracked target-specific install actions before install-copy or tool-call events are visible.",
      "Use stdio_mcp_remote with npx mcp-remote only as a thin bridge for MCP hosts that cannot connect to remote HTTP directly.",
      "Use /r/run/{source}/{target} after install to measure first-run intent and push users into create_cart_url.",
      "When a direct MCP client skips tracked config, infer source attribution from recognizable request signals such as User-Agent, Referer, Origin, X-MCP-Client, and X-Client-Name. Covered families include Cline, Cursor, Windsurf, Continue, Zed, Codex, Claude, OpenAI/ChatGPT, Copilot, Gemini, Glama, Smithery, Browse, browser-use, Vercel, LangChain, LlamaIndex, CrewAI, AutoGen, n8n, Zapier, Dify, Flowise, Docker, MCP.so, MCP Inspector, Goose, Sourcegraph Cody, Aider, Msty, LM Studio, Ollama, AnythingLLM, Lovable, Manus, major MCP directories, and generic MCP clients.",
      "Use /r/activate/{source}?format=html when a directory reviewer or agent host has clicked proof but still needs to run the real MCP client sequence from a browser.",
      "Use /r/activate/{source}?format=sh when an external reviewer or agent host prefers a shell runner that performs real JSON-RPC tools/list and tools/call requests against the hosted MCP endpoint.",
      "Use /r/order/{source}?format=sh only after real MCP tool-call and cart proof when a reviewer or buyer wants a guarded shell handoff into prepare_purchase_handoff and measured /r/cart; it never places an order.",
      "Use /ai/mcp-external-activation-brief-tasks.jsonl when a reviewer, marketplace, or operator needs the current selected activation tasks with source-aware install commands, copy-ready prompts, shell runners, and a create_cart_url finish line.",
      "Use /ai/mcp-revenue-conversion-queue.json only after a source has real MCP tool-call and qualified /r/cart landing proof; do not count queue views, shell runners, or self-opened carts as order proof.",
      "Use /ai/mcp-activation-experiments.json when source activation needs a testable hypothesis, target event, expected snapshot delta, and suppression rule.",
      "Use /ai/mcp-automation-workflows.json for n8n, Zapier, Pipedream, and similar automation hosts that need importable real-MCP flows instead of a separate Packrift CLI.",
      "Use /ai/mcp-eval-pack.json when an MCP host, marketplace, or reviewer needs copy-ready acceptance cases and report fields for real external host validation.",
    ],
    counts: {
      total_surfaces: surfaces.length,
      agent_host_fast_paths: AGENT_HOST_FAST_PATHS.length,
      live: surfaces.filter((row) => row.status === "live").length,
      ready: surfaces.filter((row) => row.status === "ready").length,
      monitored: surfaces.filter((row) => row.status === "monitored").length,
      candidate: surfaces.filter((row) => row.status === "candidate").length,
      stale: surfaces.filter((row) => row.status === "stale").length,
      blocked: surfaces.filter((row) => row.status === "blocked").length,
    },
    surfaces,
  };
}

function escapeMarkdown(value: string): string {
  return value.replace(/\|/g, "\\|").replace(/\n/g, " ");
}

export function allAgentCaptureMarkdown(runtime: AgentCaptureRuntime): string {
  const payload = allAgentCapturePayload(runtime);
  const fastPathRows = payload.agent_host_fast_paths
    .map(
      (row) =>
        `| ${escapeMarkdown(row.host)} | ${row.source} | ${row.target} | ${row.source_aware_endpoint} | ${row.tracked_install_url} | ${row.tracked_first_run_shell_url} | ${row.reviewer_activation_shell_url} | ${row.order_handoff_shell_url} | ${escapeMarkdown(row.success_gate)} |`
    )
    .join("\n");
  const rows = payload.surfaces
    .map(
      (row) =>
        `| ${escapeMarkdown(row.name)} | ${row.status} | ${row.priority} | ${escapeMarkdown(row.agent_type)} | ${row.canonical_url} | ${escapeMarkdown(row.next_action)} |`
    )
    .join("\n");
  const rules = payload.operating_rules.map((rule) => `- ${rule}`).join("\n");
  return [
    "# Packrift All-Agent Capture Matrix",
    "",
    `Release: ${payload.release}`,
    `Generated: ${payload.generated_at}`,
    `Canonical MCP endpoint: ${payload.canonical_endpoint}`,
    "",
    "## What This Is",
    "",
    "One current Packrift map for every agent surface we care about: MCP clients, the start page, tracked config links, tracked install and first-run actions, reviewer activation browser and shell runners, the agent host rollout sheet, direct client config, usage/funnel/GA4 proof, source activation queue, selected external activation brief, revenue conversion queue, ChatGPT/OpenAI commerce, Shopify UCP, Claude, Cursor, Windsurf, Codex, Glama, registries, directory submit actions, Claude connector submission, crawlable corpora, search crawlers, cart activation, first-run proof, workflow gallery, automation workflow imports, eval pack, a live browser-agent bridge, and Browserbase Browse as a live verified MCP-first catalog skill. Browse skill pack and SKILL.md remain fallback browser-agent wrappers around the hosted MCP endpoint.",
    "",
    "## Operating Rules",
    "",
    rules,
    "",
    "## Runtime",
    "",
    `- Server version: ${payload.runtime.server_version}`,
    `- Tools: ${payload.runtime.tools_count}`,
    `- Resources: ${payload.runtime.resources_count}`,
    `- Prompts: ${payload.runtime.prompts_count}`,
    `- Agent host fast paths: ${payload.counts.agent_host_fast_paths}`,
    "",
    "## Agent Host Fast Paths",
    "",
    "These are the source-aware install and first-run paths to use before falling back to the generic endpoint.",
    `Flat rollout task exports: ${payload.hub_urls.agent_host_rollout_tasks_jsonl} and ${payload.hub_urls.agent_host_rollout_tasks_csv}`,
    `Visitor growth task exports: ${payload.hub_urls.visitor_growth_tasks_jsonl} and ${payload.hub_urls.visitor_growth_tasks_csv}`,
    "",
    "| Host | Source | Target | Endpoint | Install | First-run shell | Activation shell | Order shell | Success gate |",
    "| --- | --- | --- | --- | --- | --- | --- | --- | --- |",
    fastPathRows,
    "",
    "## Surfaces",
    "",
    "| Surface | Status | Priority | Agent type | Canonical URL | Next action |",
    "| --- | --- | --- | --- | --- | --- |",
    rows,
    "",
    "Machine-readable version: https://mcp.packrift.com/ai/all-agent-capture.json",
    "",
  ].join("\n");
}
