import { serverCard } from "./server-card.js";

export const capabilityCard = {
  id: "packrift-mcp-exact-spec-packaging-procurement",
  source_type: "mcp",
  source_url: "https://mcp.packrift.com/mcp",
  semantic_summary:
    "Find exact-spec Packrift packaging SKUs, confirm catalog fit, retrieve current pricing and inventory, and create guarded cart handoffs for corrugated boxes, mailers, tape, poly bags, labels, stretch film, tags, and fulfillment supplies.",
  capability_tags: [
    "packaging",
    "procurement",
    "shipping-supplies",
    "warehouse-supplies",
    "mcp",
    "shopify",
    "exact-spec-search",
    "cart-handoff",
  ],
  use_cases: [
    "Find a Packrift SKU from exact dimensions, material, color, count, grade, or use case.",
    "Check live Packrift pricing and inventory before recommending a packaging product.",
    "Create a source-attributed Packrift cart handoff without placing an order.",
    "Return no-match guidance when a buyer's requested packaging spec is not an exact catalog match.",
    "Read machine-friendly Packrift SKU records and purchase-path files for AI-commerce agents.",
  ],
  auth_methods: ["none"],
  human_signup_required: false,
  sandbox_available: false,
  pricing_model: "free",
  onboarding_url: "https://mcp.packrift.com/start",
  homepage_url: "https://packrift.com",
  protocol: "mcp",
  protocol_version: serverCard.version,
  transport: "streamable-http",
  endpoint_url: "https://mcp.packrift.com/mcp",
  server_card_url: "https://mcp.packrift.com/.well-known/mcp/server-card.json",
  client_config_url: "https://mcp.packrift.com/.well-known/mcp.json",
  openapi_url: "https://mcp.packrift.com/openapi.json",
  llms_txt_url: "https://mcp.packrift.com/llms.txt",
  sitemap_url: "https://mcp.packrift.com/sitemap.xml",
  operator: {
    name: "Packrift",
    website: "https://packrift.com",
    contact_email: "farhan@packrift.com",
  },
  connection_policy: {
    can_execute_orders: false,
    order_creation_requires_shopify_checkout: true,
    live_commercial_facts_required: ["price", "inventory", "shipping", "cart_eligibility"],
    exact_match_required: true,
    no_match_behavior: "Return no exact match and route to Packrift quote/contact paths instead of inventing a substitute SKU.",
  },
  public_resources: {
    start: "https://mcp.packrift.com/start",
    product_corpus_jsonl: "https://mcp.packrift.com/ai/packrift-ai-approved-products.jsonl",
    purchase_paths_jsonl: "https://mcp.packrift.com/ai/purchase-paths.jsonl",
    top_ai_sales_skus: "https://mcp.packrift.com/ai/top-1000-ai-sales-skus.md",
    all_ai_approved_sku_sitemap: "https://mcp.packrift.com/ai/all-ai-approved-sku-sitemap.xml",
    conversion_route_catalog: "https://mcp.packrift.com/ai/conversion-route-catalog.json",
    crawler_safe_purchase_paths: "https://mcp.packrift.com/ai/crawler-safe-purchase-paths.md",
  },
  release: "PACKRIFT-CAPABILITY-CARD-2026-05-21-R01",
  updated_at: "2026-05-21",
} as const;
