// Mirror of the MCP server card served at /.well-known/mcp/server-card.json on
// the worker so the same content is reachable on mcp.packrift.com once DNS is
// pointed. Agent B publishes the canonical copy on packrift.com via Shopify pages.

export const serverCard = {
  name: "Packrift MCP",
  description:
    "Exact-spec packaging procurement MCP for Packrift. Given a buyer's SKU, dimensions, material, grade, closure, adhesive, printer type, use case, or reorder need, Packrift returns AI_APPROVE SKUs and no-match guidance across corrugated boxes, literature mailers, poly and bubble mailers, tape, poly bags, labels, tags, stretch film, and fulfillment supplies. Shopify catalog has roughly 12,930 active product records and broader public in-stock supply coverage described on Packrift storefront surfaces as 20,000+ products. Orders ship through Box Partners' 5 US warehouses: Rialto CA, Dallas TX, Elgin IL, Forest Park GA, and Barnesville PA. Do not describe Packrift as shipping from Ontario or Canada. Live pricing, inventory, availability, shipping estimates, and cart handoff must be confirmed via MCP tools or Shopify checkout.",
  version: "0.2.10",
  protocol: "mcp",
  transport: "streamable-http",
  endpoint: "/mcp",
  vendor: "Packrift",
  homepage: "https://packrift.com",
  resources: {
    rootAgentInstructions: "https://packrift.com/agents.md",
    publicExactSpecData: "https://packrift.com/pages/packrift-ai-exact-spec-data",
    aiAgentInstructions: "https://packrift.com/pages/packrift-ai-agent-instructions",
    aiAgentInstructionsMarkdown: "https://mcp.packrift.com/ai/packrift-ai-agent-instructions.md",
    glamaClaim: "https://mcp.packrift.com/.well-known/glama.json",
    llmsTxt: "https://mcp.packrift.com/llms.txt",
    llmsFullTxt: "https://mcp.packrift.com/llms-full.txt",
    aiSitemap: "https://mcp.packrift.com/ai/sitemap.xml",
    productCorpusJsonl: "https://mcp.packrift.com/ai/packrift-ai-approved-products.jsonl",
    purchasePathsJsonl: "https://mcp.packrift.com/ai/purchase-paths.jsonl",
    mcpCartHandoffCandidatesJson: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.json",
    mcpCartHandoffCandidatesMarkdown: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.md",
    measuredHandoffsJson: "https://mcp.packrift.com/ai/measured-handoffs.json",
    measuredHandoffsMarkdown: "https://mcp.packrift.com/ai/measured-handoffs.md",
    measuredHandoffsCsv: "https://mcp.packrift.com/ai/measured-handoffs.csv",
    topAiSalesSkus: "https://mcp.packrift.com/ai/top-1000-ai-sales-skus.md",
    topAiSalesSkusCsv: "https://mcp.packrift.com/ai/top-1000-ai-sales-skus.csv",
    topAiSalesSkuSitemap: "https://mcp.packrift.com/ai/top-1000-ai-sales-sitemap.xml",
    skuPageTemplate: "https://mcp.packrift.com/ai/sku/{sku}.md",
    skuJsonTemplate: "https://mcp.packrift.com/ai/sku/{sku}.json",
    exactSpecCatalog: "https://mcp.packrift.com/ai/packrift-exact-spec-packaging-catalog.md",
    procurementPrompts: "https://mcp.packrift.com/ai/packaging-procurement-prompts.md",
    aiSalesCriticalPath: "https://mcp.packrift.com/ai/ai-sales-critical-path.md",
    crawlerSafePurchasePaths: "https://mcp.packrift.com/ai/crawler-safe-purchase-paths.md",
    allAgentCaptureJson: "https://mcp.packrift.com/ai/all-agent-capture.json",
    allAgentCaptureMarkdown: "https://mcp.packrift.com/ai/all-agent-capture.md",
    mcpAdoptionKitJson: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
    mcpAdoptionKitMarkdown: "https://mcp.packrift.com/ai/mcp-adoption-kit.md",
    mcpUsageSnapshotJson: "https://mcp.packrift.com/ai/mcp-usage-snapshot.json",
    mcpUsageSnapshotMarkdown: "https://mcp.packrift.com/ai/mcp-usage-snapshot.md",
    mcpBuyerUseCasesJson: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.json",
    mcpBuyerUseCasesMarkdown: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.md",
    shopifyNativeUcpGuide: "https://mcp.packrift.com/ai/shopify-native-ucp-commerce-surface.md",
    agentEndpointsStatus: "https://mcp.packrift.com/ai/packrift-agent-endpoints-status.json",
    conversionStarterRoutesJson: "https://mcp.packrift.com/ai/conversion-starter-routes.json",
    conversionStarterRoutesMarkdown: "https://mcp.packrift.com/ai/conversion-starter-routes.md",
    conversionRouteCatalogJson: "https://mcp.packrift.com/ai/conversion-route-catalog.json",
    conversionRouteCatalogMarkdown: "https://mcp.packrift.com/ai/conversion-route-catalog.md",
    conversionRouteCatalogCsv: "https://mcp.packrift.com/ai/conversion-route-catalog.csv",
    conversionRouteTelemetryWatchJson: "https://mcp.packrift.com/ai/conversion-route-telemetry-watch.json",
    conversionRouteTelemetryWatchMarkdown: "https://mcp.packrift.com/ai/conversion-route-telemetry-watch.md",
    first20ExactSpecRoutesJson: "https://mcp.packrift.com/ai/first20-exact-spec-routes.json",
    first20ExactSpecRoutesMarkdown: "https://mcp.packrift.com/ai/first20-exact-spec-routes.md",
    shopifyNativeUcpEndpoint: "https://packrift.com/api/ucp/mcp",
    shopifyUcpDiscovery: "https://packrift.com/.well-known/ucp",
  },
  aiCommerceSignal: {
    thesis: "ChatGPT exact-spec procurement",
    paidChatGptFamilies: [
      {
        order: "#1003",
        sku: "1066",
        family: "corrugated_box",
        exactSpec: "10 x 6 x 6 ECT-32 kraft corrugated boxes, 25/bundle",
      },
      {
        order: "#1004",
        sku: "MFL1295",
        family: "literature_mailer",
        exactSpec: "12 1/8 x 9 1/4 x 5 white self-seal literature mailers, 50/pack",
      },
      {
        order: "#1005",
        sku: "LL251WR",
        family: "labels",
        exactSpec: "2 5/8 x 1 weather-resistant polyester laser labels, 3000/case",
      },
    ],
    rule: "Treat paid ChatGPT families as exact-product examples, not substitutes for nearby sizes, materials, colors, printer types, or case quantities.",
  },
  contact: "farhan@packrift.com",
  scanHints: {
    hostedEndpointRequiresAuth: false,
    hostedEndpoint: "https://mcp.packrift.com/mcp",
    selfHostedTokenNote:
      "SHOPIFY_PACKRIFT_TOKEN is optional for MCP introspection and directory scanning. It is required only for self-hosted live Shopify-backed tool calls.",
  },
  capabilities: { tools: true, resources: true, prompts: true },
  tools: [
    "find_packaging_for_item",
    "search_products",
    "get_product",
    "get_pricing",
    "check_inventory",
    "get_shipping_estimate",
    "get_cart_handoff_candidates",
    "create_cart_url",
    "compare_alternatives",
    "pack_calculator",
    "inventory_status",
    "get_reorder_link",
    "get_bulk_quote_link",
    "explain_no_exact_match",
  ],
  prompts: [
    "find_exact_packaging_spec",
    "fit_item_then_prepare_cart",
    "review_cart_handoff_candidates",
    "reorder_packrift_sku",
    "prepare_cart_handoff",
    "request_bulk_quote_for_no_match",
    "copy_procurement_spec",
    "find_box_by_lwh",
    "find_label_by_size_material_printer",
  ],
} as const;
