// Mirror of the MCP server card served at /.well-known/mcp/server-card.json on
// the worker so the same content is reachable on mcp.packrift.com once DNS is
// pointed. Agent B publishes the canonical copy on packrift.com via Shopify pages.

export const serverCard = {
  name: "Packrift MCP",
  description:
    "Exact-spec packaging procurement MCP for Packrift. Given a buyer's SKU, dimensions, material, grade, closure, adhesive, printer type, use case, or reorder need, Packrift returns AI_APPROVE SKUs and no-match guidance across corrugated boxes, literature mailers, poly and bubble mailers, tape, poly bags, labels, tags, stretch film, and fulfillment supplies. Shopify catalog has roughly 12,930 active product records and broader public in-stock supply coverage described on Packrift storefront surfaces as 20,000+ products. Orders ship through Box Partners' 5 US warehouses: Rialto CA, Dallas TX, Elgin IL, Forest Park GA, and Barnesville PA. Use only this US fulfillment network unless a live Packrift source confirms otherwise. Live pricing, inventory, availability, shipping estimates, and cart handoff must be confirmed via MCP tools or Shopify checkout.",
  version: "0.3.0",
  protocol: "mcp",
  transport: "streamable-http",
  endpoint: "/mcp",
  vendor: "Packrift",
  homepage: "https://packrift.com",
  resources: {
    rootAgentInstructions: "https://packrift.com/agents.md",
    publicExactSpecData: "https://packrift.com/pages/packrift-ai-exact-spec-data",
    aiAgentInstructions: "https://packrift.com/pages/packrift-ai-agent-instructions",
    aiAgentInstructionsMarkdown: "https://mcp.packrift.com/ai/packrift-ai-agent-instructions.md",
    mcpStart: "https://mcp.packrift.com/start",
    mcpTrackedStartTemplate: "https://mcp.packrift.com/r/start/{source}",
    mcpTrackedConfigTemplate: "https://mcp.packrift.com/r/config/{source}",
    mcpTrackedConfigGeneric: "https://mcp.packrift.com/r/config/generic",
    mcpStartJson: "https://mcp.packrift.com/ai/mcp-start.json",
    mcpStartMarkdown: "https://mcp.packrift.com/ai/mcp-start.md",
    glamaClaim: "https://mcp.packrift.com/.well-known/glama.json",
    llmsTxt: "https://mcp.packrift.com/llms.txt",
    llmsFullTxt: "https://mcp.packrift.com/llms-full.txt",
    rootAgentWebManifest: "https://mcp.packrift.com/agent.json",
    agentWebManifest: "https://mcp.packrift.com/.well-known/agent.json",
    capabilityCard: "https://mcp.packrift.com/.well-known/capability-card.json",
    rootMcpJson: "https://mcp.packrift.com/mcp.json",
    wellKnownMcpJson: "https://mcp.packrift.com/.well-known/mcp.json",
    openapiJson: "https://mcp.packrift.com/openapi.json",
    wellKnownOpenapiJson: "https://mcp.packrift.com/.well-known/openapi.json",
    aiPluginJson: "https://mcp.packrift.com/ai-plugin.json",
    wellKnownAiPluginJson: "https://mcp.packrift.com/.well-known/ai-plugin.json",
    aiSitemap: "https://mcp.packrift.com/ai/sitemap.xml",
    productCorpusJsonl: "https://mcp.packrift.com/ai/packrift-ai-approved-products.jsonl",
    purchasePathsJsonl: "https://mcp.packrift.com/ai/purchase-paths.jsonl",
    mcpCartHandoffCandidatesJson: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.json",
    mcpCartHandoffCandidatesMarkdown: "https://mcp.packrift.com/ai/mcp-cart-handoff-candidates.md",
    measuredHandoffsJson: "https://mcp.packrift.com/ai/measured-handoffs.json",
    measuredHandoffsMarkdown: "https://mcp.packrift.com/ai/measured-handoffs.md",
    measuredHandoffsCsv: "https://mcp.packrift.com/ai/measured-handoffs.csv",
    topAiSalesSkus: "https://mcp.packrift.com/ai/top-1000-ai-sales-skus.md",
    topAiSalesSkusCsv: "https://mcp.packrift.com/ai/top-1000-ai-sales-skus.csv",
    topAiSalesSkuSitemap: "https://mcp.packrift.com/ai/top-1000-ai-sales-sitemap.xml",
    openaiStrictPublicProductFeedTsv:
      "https://mcp.packrift.com/ai/packrift-openai-products-strict-stable-current.tsv",
    openaiProductFeedManifest: "https://mcp.packrift.com/ai/openai-product-feed-manifest.json",
    openaiPreferredDirectProductFeedTsv:
      "https://mcp.packrift.com/ai/packrift-openai-products-preferred-direct-current.tsv",
    openaiPreferredDirectProductFeedGzip:
      "https://mcp.packrift.com/ai/packrift-openai-products-preferred-direct-current.tsv.gz",
    skuPageTemplate: "https://mcp.packrift.com/ai/sku/{sku}.md",
    skuJsonTemplate: "https://mcp.packrift.com/ai/sku/{sku}.json",
    exactSpecCatalog: "https://mcp.packrift.com/ai/packrift-exact-spec-packaging-catalog.md",
    procurementPrompts: "https://mcp.packrift.com/ai/packaging-procurement-prompts.md",
    aiSalesCriticalPath: "https://mcp.packrift.com/ai/ai-sales-critical-path.md",
    crawlerSafePurchasePaths: "https://mcp.packrift.com/ai/crawler-safe-purchase-paths.md",
    allAgentCaptureJson: "https://mcp.packrift.com/ai/all-agent-capture.json",
    allAgentCaptureMarkdown: "https://mcp.packrift.com/ai/all-agent-capture.md",
    mcpAgentHostRolloutJson: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.json",
    mcpAgentHostRolloutMarkdown: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.md",
    mcpAgentHostRolloutHtml: "https://mcp.packrift.com/ai/mcp-agent-host-rollout.html",
    mcpAgentHostRolloutTasksJsonl: "https://mcp.packrift.com/ai/mcp-agent-host-rollout-tasks.jsonl",
    mcpAgentHostRolloutTasksCsv: "https://mcp.packrift.com/ai/mcp-agent-host-rollout-tasks.csv",
    mcpAdoptionKitJson: "https://mcp.packrift.com/ai/mcp-adoption-kit.json",
    mcpAdoptionKitMarkdown: "https://mcp.packrift.com/ai/mcp-adoption-kit.md",
    mcpInstallMatrixJson: "https://mcp.packrift.com/ai/mcp-install-matrix.json",
    mcpInstallMatrixMarkdown: "https://mcp.packrift.com/ai/mcp-install-matrix.md",
    mcpClientConfigJson: "https://mcp.packrift.com/ai/mcp-client-config.json",
    mcpClientConfigMarkdown: "https://mcp.packrift.com/ai/mcp-client-config.md",
    mcpUsageSnapshotJson: "https://mcp.packrift.com/ai/mcp-usage-snapshot.json",
    mcpUsageSnapshotMarkdown: "https://mcp.packrift.com/ai/mcp-usage-snapshot.md",
    mcpSourceActivationQueueJson: "https://mcp.packrift.com/ai/mcp-source-activation-queue.json",
    mcpSourceActivationQueueMarkdown: "https://mcp.packrift.com/ai/mcp-source-activation-queue.md",
    mcpSourceActivationQueueHtml: "https://mcp.packrift.com/ai/mcp-source-activation-queue.html",
    mcpRevenueConversionQueueJson: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.json",
    mcpRevenueConversionQueueMarkdown: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.md",
    mcpRevenueConversionQueueHtml: "https://mcp.packrift.com/ai/mcp-revenue-conversion-queue.html",
    mcpBuyerOrderHandoffsJson: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.json",
    mcpBuyerOrderHandoffsMarkdown: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.md",
    mcpBuyerOrderHandoffsHtml: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs.html",
    mcpBuyerOrderHandoffsTasksJsonl: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs-tasks.jsonl",
    mcpBuyerOrderHandoffsTasksCsv: "https://mcp.packrift.com/ai/mcp-buyer-order-handoffs-tasks.csv",
    mcpSourceActivationSitemap: "https://mcp.packrift.com/ai/mcp-source-activation-sitemap.xml",
    mcpSourceActivationPacketTemplate: "https://mcp.packrift.com/ai/mcp-source-activation/{source}.json",
    mcpSourceActivationPacketCline: "https://mcp.packrift.com/ai/mcp-source-activation/cline_mcp_marketplace.json",
    mcpActivationExperimentsJson: "https://mcp.packrift.com/ai/mcp-activation-experiments.json",
    mcpActivationExperimentsMarkdown: "https://mcp.packrift.com/ai/mcp-activation-experiments.md",
    mcpActivationExperimentsHtml: "https://mcp.packrift.com/ai/mcp-activation-experiments.html",
    mcpActivationWaveJson: "https://mcp.packrift.com/ai/mcp-activation-wave.json",
    mcpActivationWaveMarkdown: "https://mcp.packrift.com/ai/mcp-activation-wave.md",
    mcpActivationWaveHtml: "https://mcp.packrift.com/ai/mcp-activation-wave.html",
    mcpActivationWaveTasksJsonl: "https://mcp.packrift.com/ai/mcp-activation-wave-tasks.jsonl",
    mcpActivationWaveTasksCsv: "https://mcp.packrift.com/ai/mcp-activation-wave-tasks.csv",
    mcpActivationWaveRunnerShell: "https://mcp.packrift.com/ai/mcp-activation-wave-runner.sh",
    mcpExternalActivationBriefJson: "https://mcp.packrift.com/ai/mcp-external-activation-brief.json",
    mcpExternalActivationBriefMarkdown: "https://mcp.packrift.com/ai/mcp-external-activation-brief.md",
    mcpExternalActivationBriefHtml: "https://mcp.packrift.com/ai/mcp-external-activation-brief.html",
    mcpExternalActivationBriefTasksJsonl: "https://mcp.packrift.com/ai/mcp-external-activation-brief-tasks.jsonl",
    mcpExternalActivationBriefTasksCsv: "https://mcp.packrift.com/ai/mcp-external-activation-brief-tasks.csv",
    mcpExternalActivationBriefRunnerShell: "https://mcp.packrift.com/ai/mcp-external-activation-brief-runner.sh",
    mcpActivationCommandCenter: "https://mcp.packrift.com/r/activate",
    mcpBuyerUseCasesJson: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.json",
    mcpBuyerUseCasesMarkdown: "https://mcp.packrift.com/ai/mcp-buyer-use-cases.md",
    mcpCartActivationJson: "https://mcp.packrift.com/ai/mcp-cart-activation.json",
    mcpCartActivationMarkdown: "https://mcp.packrift.com/ai/mcp-cart-activation.md",
    mcpFirstRunProofJson: "https://mcp.packrift.com/ai/mcp-first-run-proof.json",
    mcpFirstRunProofMarkdown: "https://mcp.packrift.com/ai/mcp-first-run-proof.md",
    mcpWorkflowGalleryJson: "https://mcp.packrift.com/ai/mcp-workflow-gallery.json",
    mcpWorkflowGalleryMarkdown: "https://mcp.packrift.com/ai/mcp-workflow-gallery.md",
    mcpSourceListingReadinessJson: "https://mcp.packrift.com/ai/mcp-source-listing-readiness.json",
    mcpSourceListingReadinessMarkdown: "https://mcp.packrift.com/ai/mcp-source-listing-readiness.md",
    browserAgentBridgeJson: "https://mcp.packrift.com/ai/browser-agent-bridge.json",
    browserAgentBridgeMarkdown: "https://mcp.packrift.com/ai/browser-agent-bridge.md",
    rootBrowserSkillMarkdown: "https://mcp.packrift.com/SKILL.md",
    browserbaseBrowseSkillPackJson: "https://mcp.packrift.com/ai/browserbase-browse-skill-pack.json",
    browserbaseBrowseSkillPackMarkdown: "https://mcp.packrift.com/ai/browserbase-browse-skill-pack.md",
    browserbaseBrowseSkillMarkdown: "https://mcp.packrift.com/ai/browserbase-browse/SKILL.md",
    mcpDirectoryRefreshJson: "https://mcp.packrift.com/ai/mcp-directory-refresh.json",
    mcpDirectoryRefreshMarkdown: "https://mcp.packrift.com/ai/mcp-directory-refresh.md",
    mcpDirectorySubmitActionsJson: "https://mcp.packrift.com/ai/mcp-directory-submit-actions.json",
    mcpDirectorySubmitActionsMarkdown: "https://mcp.packrift.com/ai/mcp-directory-submit-actions.md",
    mcpReviewerActivationJson: "https://mcp.packrift.com/ai/mcp-reviewer-activation.json",
    mcpReviewerActivationMarkdown: "https://mcp.packrift.com/ai/mcp-reviewer-activation.md",
    mcpTrackedReviewerActivationTemplate: "https://mcp.packrift.com/r/activate/{source}",
    mcpTrackedReviewerActivationHtmlTemplate: "https://mcp.packrift.com/r/activate/{source}?format=html",
    mcpTrackedReviewerActivationHtmlGeneric: "https://mcp.packrift.com/r/activate/generic?format=html",
    mcpTrackedReviewerActivationShellTemplate: "https://mcp.packrift.com/r/activate/{source}?format=sh",
    mcpTrackedReviewerActivationShellGeneric: "https://mcp.packrift.com/r/activate/generic?format=sh",
    shopifyNativeUcpGuide: "https://mcp.packrift.com/ai/shopify-native-ucp-commerce-surface.md",
    agentEndpointsStatus: "https://mcp.packrift.com/ai/packrift-agent-endpoints-status.json",
    conversionStarterRoutesJson: "https://mcp.packrift.com/ai/conversion-starter-routes.json",
    conversionStarterRoutesMarkdown: "https://mcp.packrift.com/ai/conversion-starter-routes.md",
    conversionRouteCatalogJson: "https://mcp.packrift.com/ai/conversion-route-catalog.json",
    conversionRouteCatalogMarkdown: "https://mcp.packrift.com/ai/conversion-route-catalog.md",
    conversionRouteCatalogCsv: "https://mcp.packrift.com/ai/conversion-route-catalog.csv",
    conversionRouteTelemetryWatchJson: "https://mcp.packrift.com/ai/conversion-route-telemetry-watch.json",
    conversionRouteTelemetryWatchMarkdown: "https://mcp.packrift.com/ai/conversion-route-telemetry-watch.md",
    first20ExactSpecRoutesJson: "https://mcp.packrift.com/ai/first20-exact-spec-routes.json",
    first20ExactSpecRoutesMarkdown: "https://mcp.packrift.com/ai/first20-exact-spec-routes.md",
    shopifyNativeUcpEndpoint: "https://packrift.com/api/ucp/mcp",
    shopifyUcpDiscovery: "https://packrift.com/.well-known/ucp",
  },
  aiCommerceSignal: {
    thesis: "ChatGPT exact-spec procurement",
    paidChatGptFamilies: [
      {
        order: "#1003",
        sku: "1066",
        family: "corrugated_box",
        exactSpec: "10 x 6 x 6 ECT-32 kraft corrugated boxes, 25/bundle",
      },
      {
        order: "#1004",
        sku: "MFL1295",
        family: "literature_mailer",
        exactSpec: "12 1/8 x 9 1/4 x 5 white self-seal literature mailers, 50/pack",
      },
      {
        order: "#1005",
        sku: "LL251WR",
        family: "labels",
        exactSpec: "2 5/8 x 1 weather-resistant polyester laser labels, 3000/case",
      },
    ],
    rule: "Treat paid ChatGPT families as exact-product examples, not substitutes for nearby sizes, materials, colors, printer types, or case quantities.",
  },
  contact: "farhan@packrift.com",
  scanHints: {
    hostedEndpointRequiresAuth: false,
    hostedEndpoint: "https://mcp.packrift.com/mcp",
    reviewerActivationBrowserRunner: "https://mcp.packrift.com/r/activate/generic?format=html",
    reviewerActivationShellRunner: "https://mcp.packrift.com/r/activate/generic?format=sh",
    selfHostedTokenNote:
      "SHOPIFY_PACKRIFT_TOKEN is optional for MCP introspection and directory scanning. It is required only for self-hosted live Shopify-backed tool calls.",
  },
  capabilities: { tools: true, resources: true, prompts: true },
  tools: [
    "find_packaging_for_item",
    "search_products",
    "get_product",
    "get_pricing",
    "check_inventory",
    "get_shipping_estimate",
    "get_cart_handoff_candidates",
    "create_cart_url",
    "prepare_purchase_handoff",
    "compare_alternatives",
    "pack_calculator",
    "inventory_status",
    "get_reorder_link",
    "get_bulk_quote_link",
    "explain_no_exact_match",
  ],
  prompts: [
    "find_exact_packaging_spec",
    "fit_item_then_prepare_cart",
    "review_cart_handoff_candidates",
    "reorder_packrift_sku",
    "prepare_cart_handoff",
    "request_bulk_quote_for_no_match",
    "copy_procurement_spec",
    "find_box_by_lwh",
    "find_label_by_size_material_printer",
  ],
} as const;
